version: '3.9'
services:
  evaluation-service:
    build: .
    image: evaluation-service:latest
    container_name: evaluation-service
    ports:
      - "3002:3002"
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock    # <--- give access to Docker daemon
    environment:
      - NODE_ENV=development
    tty: true

volumes:
  node_modules:
